#pragma once

#include <string>

namespace tsp {

constexpr std::string_view help{
    "  == TSP: Task Spooler for HPC == \n"
    " A topology-aware serverless task spooler. tsp detects other TSP "
    "instances\n"
    " on the same node and determines which CPU cores those instances are "
    "bound\n"
    " to. When sufficient cores are free, TSP will allow its queued task to "
    "run\n"
    " and bind it to the first N available cores. State is managed through an "
    "\n"
    " sqlite3 database which can be queried using the TSP command.\n\n"
    " When 'Job Querying Options' are present, the first such option will\n"
    " be used to determine the output of TSP. If none are present, then TSP\n"
    " will assume it is being used to run a command. The exception to this\n"
    " is when no arguments are given, TSP will act as if '-l' has been\n"
    " passed\n\n"
    " A 'timeout' mode is available when the --timeout flag is passed to TSP.\n"
    " In this mode, TSP will monitor all currently running TSP instances and "
    "kill\n"
    " any that exceed a pre-designated time limit. An idle timeout is used to "
    "end\n"
    " TSP in this mode. If no other running TSP processes are detected over "
    "the idle\n"
    " timeout period, TSP will automatically shut down\n\n"
// Disable memprof on not-linux systems
#ifdef __linux__
    " A memory profiling mode is available when the --memprof flag is passed\n"
    " to TSP. In this mode, TSP will periodically inspect the memory usage of\n"
    " all running TSP processes and all of their associated subprocesses. "
    "Like\n"
    " timeout mode, when no other TSP-controlled running jobs are detected "
    "over\n"
    " an idle timeout period, TSP will automatically shut down.\n\n"
#endif
    "Usage: {} [OPTION]... [COMMAND...] \n\n"
    "Global options:\n"
    "  -f, --no-fork          Do not fork the original TSP process to the "
    "background\n"
    "  -v, --verbose          Print status messages when job starts and "
    "ends\n\n"
    "Job Submission Options:\n"
    "  -n, --no-output        Do not store stdout/stderr of COMMAND\n"
    "  -N, --nslots=SLOTS     Number of physical cores required (default is "
    "1)\n"
    "  -E, --separate-stderr  Store stdout and stderr in different files\n"
    "  -L, --label=LABEL      Add a label to the task to facilitate simpler "
    "querying\n"
    "  -r, --rerun=ID         Rerun job with id ID\n\n"
    "Timeout Mode Options:\n"
    "      --timeout          Run the TSP timeout function\n"
    "  -p  --polling-interval=T\n"
    "                         Poll for running TSP instances every T seconds. "
    "Default is 10.\n"
    "  -I  --idle-timeout=T   If TSP has not detected any running jobs in T "
    "seconds, exit.\n"
    "                         Default is 30\n"
    "  -T  --job-timeout=T    How many seconds other TSP instances should be "
    "allowed to run.\n"
    "                         Default is 7200 (2 hours)\n\n"
// Disable memprof on not-linux systems
#ifdef __linux__
    "Memory Profiling Mode Options:\n"
    "      --memprof          Run the TSP memory profiling function\n"
    "  -p  --polling-interval=T\n"
    "                         Poll for running TSP instances every T seconds. "
    "Default is 10.\n"
    "  -I  --idle-timeout=T   If TSP has not detected any running jobs in T "
    "seconds, exit.\n"
    "                         Default is 30\n\n"
#endif
    "Job Querying Options:\n"
    "  -l, --list             Show the job list (default action)\n"
    "      --list-failed      Show the list of failed jobs\n"
    "      --list-running     Show the list of running jobs\n"
    "      --list-queued      Show the list of queued jobs\n"
    "      --list-finished    Show the list of finished jobs\n"
    "      --print-queue-time=[ID]\n"
    "      --print-run-time=[ID]\n"
    "      --print-total-time=[ID]\n"
    "                         Show the queue/run/total (queue+run) time of job "
    "[ID].\n"
    "                         (latest if ID is omitted)\n"
    "  -i, --info=[ID]        Show detailed info for job [ID] (latest if ID is "
    "omitted)\n"
    "  -o, --stdout=[ID]      Display the output of the job [ID] (latest if ID "
    "\n"
    "                         is omitted)\n"
    "  -e, --stderr=[ID]      If -E was provided, display the error file of \n"
    "                         the job [ID] (latest if ID is omitted)\n"
    "      --db-path          Output the path to the database\n"
    "      --gh-summary       Output summary info for github actions\n\n"
    "Other Options:\n"
    "  -h, --help    display this help and exit\n"};
} // namespace tsp